export const metadata = {
  title: "TODO",
  description: "Generated by Next.js"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {/* <Header /> */}
      {children}
    </>
  );
}
