import { AppSidebar } from "../components/ui/app-sidebar";
import { SidebarProvider, SidebarTrigger, useSidebar } from "../components/ui/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-screen h-screen max-h-screen">
            <SidebarTrigger className="mt-2 ml-2" />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
