import { SidebarTrigger } from "../components/ui/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="w-full h-screen max-h-screen overflow-hidden bg-gray-50">
      <SidebarTrigger />
      {children}
    </main>
  );
}
